<Project>

  <PropertyGroup>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>

    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <Deterministic>true</Deterministic>
    <DebugType>portable</DebugType>

    <Authors>NicholasC</Authors>
    <Company>Netherite</Company>
    <Copyright>Copyright © Netherite</Copyright>

    <GenerateDocumentationFile>true</GenerateDocumentationFile>

    <BaseOutputPath>$(MSBuildThisFileDirectory)artifacts/bin/</BaseOutputPath>
    <BaseIntermediateOutputPath>$(MSBuildThisFileDirectory)artifacts/obj/</BaseIntermediateOutputPath>

  </PropertyGroup>

</Project>
